# Generated by Django 4.1 on 2022-10-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('altex_price', models.CharField(max_length=100)),
                ('emag_price', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('url_altex', models.URLField(blank=True, null=True)),
                ('url_emag', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
