# Generated by Django 4.1 on 2022-10-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('responsible', models.CharField(max_length=100)),
                ('deadline', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Done', 'Done'), ('Not started', 'Not started')], default='Not started', max_length=20)),
                ('percentage', models.CharField(choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='0%', max_length=20)),
                ('comment', models.CharField(default='To be modified', max_length=1000)),
                ('active', models.BooleanField(default=0)),
                ('file', models.FileField(default='No file', upload_to='store/')),
            ],
        ),
    ]
