# Generated by Django 4.1 on 2022-08-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0003_rename_visualizations_visualization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='active',
            field=models.BooleanField(default=0),
        ),
    ]
