# Generated by Django 4.1 on 2022-08-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0004_alter_visualization_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='estimated_duration',
            field=models.CharField(default='To be modified', max_length=100),
        ),
    ]
