# Generated by Django 4.1 on 2022-08-31 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0005_visualization_estimated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 10, 51, 11, 834247)),
        ),
    ]
