# Generated by Django 4.1 on 2022-08-31 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0006_visualization_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='comment',
            field=models.CharField(default='To be modified', max_length=1000),
        ),
        migrations.AddField(
            model_name='visualization',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Done', 'Done'), ('Not started', 'Not started')], default='Not started', max_length=20),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 10, 53, 19, 343824)),
        ),
    ]
