# Generated by Django 4.1 on 2022-08-31 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0007_visualization_comment_visualization_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualization',
            name='due_date',
        ),
        migrations.AddField(
            model_name='visualization',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 11, 26, 56, 547777)),
        ),
    ]
