# Generated by Django 4.1 on 2022-08-31 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0008_remove_visualization_due_date_visualization_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 11, 26, 59, 526268)),
        ),
    ]
