# Generated by Django 4.1 on 2022-08-31 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0010_alter_visualization_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='percentage',
            field=models.CharField(choices=[('0%', '0%'), ('0%', '0%'), ('0%', '0%'), ('0%', '0%'), ('0%', '0%'), ('0%', '0%'), ('0%', '0%'), ('0%', '0%'), ('0%', '0%'), ('0%', '0%'), ('0%', '0%')], default='0%', max_length=20),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 11, 45, 3, 297154)),
        ),
    ]
