# Generated by Django 4.1 on 2022-08-31 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0011_visualization_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 8, 31, 11, 49, 8, 161765)),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
