# Generated by Django 4.1 on 2022-11-09 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicatie1', '0012_alter_visualization_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='author',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
