# Generated by Django 4.1 on 2022-09-06 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0016_alter_visualization_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='today',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
