# Generated by Django 4.1 on 2022-09-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0017_visualization_today_alter_visualization_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualization',
            name='today',
        ),
    ]
