# Generated by Django 4.1 on 2022-09-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0020_remove_visualization_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualization',
            name='estimated_duration',
        ),
    ]
