# Generated by Django 4.1 on 2022-09-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0021_remove_visualization_estimated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='pdf',
            field=models.FileField(default='No pdf', upload_to='details/pdfs'),
        ),
    ]
