# Generated by Django 4.1 on 2022-09-09 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0022_visualization_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualization',
            name='pdf',
        ),
    ]
