# Generated by Django 4.1 on 2022-09-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0023_remove_visualization_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
