# Generated by Django 4.1 on 2022-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0025_alter_visualization_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='file',
            field=models.FileField(null=True, upload_to='store/'),
        ),
    ]
