# Generated by Django 4.1 on 2022-09-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0026_alter_visualization_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='file',
            field=models.FileField(default='No file', upload_to=''),
        ),
    ]
