# Generated by Django 4.1.1 on 2022-09-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0028_alter_visualization_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualization',
            name='deadline',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='file',
            field=models.FileField(default='No file', upload_to='store/'),
        ),
    ]
